// flow-typed signature: 2b1b3649b5cec61cfc4d5f53e2c8875c
// flow-typed version: <<STUB>>/editor_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'editor/example/edit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'editor/example/edit.js' {
  declare module.exports: $Exports<'editor/example/edit'>;
}
declare module 'editor/index' {
  declare module.exports: $Exports<'editor'>;
}
declare module 'editor/index.js' {
  declare module.exports: $Exports<'editor'>;
}
